### ISSUE TITLE
Use XDG_DATA_HOME  or XDG_CONFIG_HOME environment variable

### ISSUE THREAD

**Issue by strafe** [Vendicated/VencordInstaller#10]
It's somewhat of a standard on Linux and macOS

**Comment by Vendicated** [comment]
Use where?

**Comment by ArjixWasTaken** [comment]
maybe for the vencord config files, although there is another XDG var for that, and using the XDG HOME var would make other people (like you) angry

**Comment by Vendicated** [comment]
the Vencord config files already respect your xdg config. https://github.com/ProtonMail/go-appdir/blob/master/appdir_xdg.go#L15-L18

**Comment by Vendicated** [comment]
the likely cause is that you're running as root and not copying over the XDG_CONFIG_HOME variable, in which case you should make sudo copy it over

**Comment by strafe** [comment]
Just referencing the screenshot in the README
<img width="593" alt="CleanShot 2022-12-10 at 22 36 36@2x" src="https://user-images.githubusercontent.com/15663890/206877918-e787e625-c5de-427d-986b-216a23a0f013.png">

**Comment by Vendicated** [comment]
yes this is to customise it further

**Comment by Vendicated** [comment]
as in, a location that isnt ur XDG_CONFIG_HOME

**Comment by strafe** [comment]
Confused. I have my `XDG_CONFIG_HOME` set to `/Users/adam/.config` and when I run the installer I see this:

<img width="1011" alt="CleanShot 2022-12-11 at 00 23 02@2x" src="https://user-images.githubusercontent.com/15663890/206880678-7c5ed701-4fec-4cd2-9084-417ccb6069b9.png">

This is on macOS so I'm running the installer with the right-click open method as my own user

**Comment by strafe** [comment]
Ah I see, the library you're using doesn't think people on macOS want to use XDG environment variables so it has other defaults

**Comment by Vendicated** [comment]
apple does not follow the XDG spec so it isn't supported on Mac

**Comment by strafe** [comment]
I mean, it's up to the developer what behaviour to implement. What I have generally seen is that if `XDG_CONFIG_HOME` is set on macOS, then it's respected as the user has gone to the effort of setting it, so it's probably their preference.
