### ISSUE TITLE
When running the installer script in Wayland, it fails due to not recognizing X11

### ISSUE THREAD

**Issue by zoro11031** [Vendicated/VencordInstaller#2]
```
2022/10/28 14:13:49 PlatformError: X11: Failed to open display :0
panic: NotInitialized: The GLFW library is not initialized

goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.acceptError({0x0, 0x0, 0x10004?})
	/home/runner/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20220320163800-277f93cfa958/error.go:174 +0x1d9
github.com/go-gl/glfw/v3.3/glfw.panicError(...)
	/home/runner/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20220320163800-277f93cfa958/error.go:185
github.com/go-gl/glfw/v3.3/glfw.WindowHint(0xc0004a5e68?, 0x6fb29a?)
	/home/runner/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20220320163800-277f93cfa958/window.go:275 +0x3f
github.com/AllenDang/imgui-go.NewGLFW({0x31047c8?}, {0xa3b303, 0x11}, 0xac21b0?, 0x9dd740?, 0x0)
	/home/runner/go/pkg/mod/github.com/!allen!dang/imgui-go@v1.12.1-0.20220322114136-499bbf6a42ad/PlatformGlfw.go:68 +0xba
github.com/AllenDang/giu.NewMasterWindow({0xa3b303, 0x11}, 0x4b0, 0x320, 0xa0?)
	/home/runner/go/pkg/mod/github.com/!allen!dang/giu@v0.6.2/MasterWindow.go:66 +0x10b
main.main()
	/home/runner/work/VencordInstaller/VencordInstaller/main.go:354 +0x75
```

**Comment by Vendicated** [comment]
Hey, have you had a chance to try this?

**Comment by KaiserBloo** [comment]
> Actually it seems to support Wayland out of the box, could you try if this binary works on Wayland?
> 
> [VencordInstaller.zip](https://github.com/Vendicated/Vencord/files/9891404/VencordInstaller.zip)
> 
> or build from source via
> 
> ```shell
> go build --ldflags="-s -w -X 'main.InstallerGitHasha=$(git rev-parse --short HEAD)'" --tags wayland
> ```

Not OP, but just tried on wayland myself with that installer and got the following error:
```
Using UserConfig
Checking if /home/kaiser/.config/Vencord/dist exists: Yes
Fetching https://api.github.com/repos/Vendicated/Vencord/releases/latest
Checking if /opt/discord-canary/resources exists: Yes
Checking if /opt/discord-canary/resources/app exists: No
Found Discord install at  /opt/discord-canary
2022/11/19 01:24:22 PlatformError: Wayland: Window position retrieval not supported
2022/11/19 01:24:22 PlatformError: Wayland: Window position setting not supported
Finished fetching GitHub Data
Latest hash is 8f2c247 Local Install is outdated!
xdg_wm_base@10: error 4: wl_surface@20 already has a buffer committed
2022/11/19 01:24:22 PlatformError: Wayland: Focusing a window requires user interaction
```

**Comment by Vendicated** [comment]
@KaiserBloo "got the following error" = crash? Black screen? Or what exactly happens

**Comment by KaiserBloo** [comment]
> @KaiserBloo "got the following error" = crash? Black screen? Or what exactly happens

just nothing happens, that error is spat out in the terminal and no window appears or anything

**Comment by Vendicated** [comment]
okay thanks!

It's hard for me to test wayland stuffs cause I use X11 but I'll spin up some wayland session soon and try to fix

**Comment by Vendicated** [comment]
I think I fixed it, could you please test if this binary works? 
[VencordInstaller.zip](https://github.com/Vendicated/VencordInstaller/files/10118722/VencordInstaller.zip)

**Comment by Cypheriel** [comment]
> I think I fixed it, could you please test if this binary works? It will still log some errors related to screen size but i think it doesn't matter? Seems to work fine anyway [VencordInstaller.zip](https://github.com/Vendicated/VencordInstaller/files/10118722/VencordInstaller.zip)

I can confirm the GUI works on my end, but I can no longer say the same for my poor Discord installation.
![image](https://user-images.githubusercontent.com/61402923/204769670-21728f2e-4400-40ac-93b1-8d40c4996e1f.png)
