### ISSUE TITLE
Running The Installer Does Nothing !

### ISSUE THREAD

**Issue by SpreadSheets650** [Vendicated/VencordInstaller#8]
How Can I Fix The Problem ?
It Is For Windows 10, But The Extension Works Fine.

The Attached Is A Video Showing The Same.

[Screen Recoding Of The Error](https://user-images.githubusercontent.com/89208925/205352632-6b2480de-bfb2-440a-9f3f-401559e2f035.webm)

**Comment by Vendicated** [comment]
Run via terminal to get an error message. You are likely using 32bit or don't have (recent enough) OpenGL support (Update your GPU driver)

**Comment by SpreadSheets650** [comment]
> Run via terminal to get an error message. You are likely using 32bit or don't have (recent enough) OpenGL support (Update your GPU driver)

This is 64 bit laptop though, 10 years old and has 0 graphics .....

**Comment by h4rldev** [comment]
Update your drivers 👍

**Comment by SpreadSheets650** [comment]
Thank You,

**Comment by Vendicated** [comment]
Did that fix it?

**Comment by SpreadSheets650** [comment]
> Did that fix it?

Yea, it did... just had to update the display adapter driver .... and thanks again
